//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWeb.TokenEx_Test {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAction", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.TokenizeFromEncryptedValueAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ValidateTokenAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.DetokenizeAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.DeleteTokenAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.GetSingleUseAuthTokenAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ProcessTransationAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.TokenAction))]
    public partial class BaseAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenExIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APIKey {
            get {
                return this.APIKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.APIKeyField, value) != true)) {
                    this.APIKeyField = value;
                    this.RaisePropertyChanged("APIKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenExID {
            get {
                return this.TokenExIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenExIDField, value) != true)) {
                    this.TokenExIDField = value;
                    this.RaisePropertyChanged("TokenExID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenizeFromEncryptedValueAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TokenizeFromEncryptedValueAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EcryptedDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TokenTypeEnum TokenSchemeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EcryptedData {
            get {
                return this.EcryptedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.EcryptedDataField, value) != true)) {
                    this.EcryptedDataField = value;
                    this.RaisePropertyChanged("EcryptedData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.TokenTypeEnum TokenScheme {
            get {
                return this.TokenSchemeField;
            }
            set {
                if ((this.TokenSchemeField.Equals(value) != true)) {
                    this.TokenSchemeField = value;
                    this.RaisePropertyChanged("TokenScheme");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTokenAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ValidateTokenAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetokenizeAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DetokenizeAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteTokenAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DeleteTokenAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSingleUseAuthTokenAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class GetSingleUseAuthTokenAction : CSWeb.TokenEx_Test.BaseAction {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTransationAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ProcessTransationAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TransactionTypeEnum TransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TransactionRequestFormatEnum TransactionRequestFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionRequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.TransactionTypeEnum TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public CSWeb.TokenEx_Test.TransactionRequestFormatEnum TransactionRequestFormat {
            get {
                return this.TransactionRequestFormatField;
            }
            set {
                if ((this.TransactionRequestFormatField.Equals(value) != true)) {
                    this.TransactionRequestFormatField = value;
                    this.RaisePropertyChanged("TransactionRequestFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string TransactionRequest {
            get {
                return this.TransactionRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionRequestField, value) != true)) {
                    this.TransactionRequestField = value;
                    this.RaisePropertyChanged("TransactionRequest");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTransactionWithPANAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ProcessTransactionWithPANAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TokenTypeEnum TokenSchemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TransactionTypeEnum TransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TransactionRequestFormatEnum TransactionRequestFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionRequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.TokenTypeEnum TokenScheme {
            get {
                return this.TokenSchemeField;
            }
            set {
                if ((this.TokenSchemeField.Equals(value) != true)) {
                    this.TokenSchemeField = value;
                    this.RaisePropertyChanged("TokenScheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.TransactionTypeEnum TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public CSWeb.TokenEx_Test.TransactionRequestFormatEnum TransactionRequestFormat {
            get {
                return this.TransactionRequestFormatField;
            }
            set {
                if ((this.TransactionRequestFormatField.Equals(value) != true)) {
                    this.TransactionRequestFormatField = value;
                    this.RaisePropertyChanged("TransactionRequestFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string TransactionRequest {
            get {
                return this.TransactionRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionRequestField, value) != true)) {
                    this.TransactionRequestField = value;
                    this.RaisePropertyChanged("TransactionRequest");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenAction", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TokenAction : CSWeb.TokenEx_Test.BaseAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.TokenTypeEnum TokenSchemeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.TokenTypeEnum TokenScheme {
            get {
                return this.TokenSchemeField;
            }
            set {
                if ((this.TokenSchemeField.Equals(value) != true)) {
                    this.TokenSchemeField = value;
                    this.RaisePropertyChanged("TokenScheme");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenTypeEnum", Namespace="")]
    public enum TokenTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sixTOKENfour = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fourTOKENfour = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOKENfour = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GUID = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SSN = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nGUID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nTOKENfour = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nTOKEN = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sixANTOKENfour = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fourANTOKENfour = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANTOKENfour = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANTOKEN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANTOKENAUTO = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASCIITOKENfour = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASCIITOKEN = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sixASCIITOKENfour = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fourASCIITOKENfour = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASCIITOKENAUTO = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sixNTOKENfour = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fourNTOKENfour = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NTOKENAUTO = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOKEN = 22,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionTypeEnum", Namespace="")]
    public enum TransactionTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authorize = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Capture = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Purchase = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refund = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Void = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reverse = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionRequestFormatEnum", Namespace="")]
    public enum TransactionRequestFormatEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XML = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JSON = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfTokenizeFromEncryptedValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfValidateToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfDetokenize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfDeleteToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfGetSingleUseAuthToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfProcessTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSWeb.TokenEx_Test.ResultOfAddToken))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfTokenizeFromEncryptedValue", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfTokenizeFromEncryptedValue : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfValidateToken", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfValidateToken : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valid {
            get {
                return this.ValidField;
            }
            set {
                if ((this.ValidField.Equals(value) != true)) {
                    this.ValidField = value;
                    this.RaisePropertyChanged("Valid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfDetokenize", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfDetokenize : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfDeleteToken", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfDeleteToken : CSWeb.TokenEx_Test.BaseResult {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfGetSingleUseAuthToken", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfGetSingleUseAuthToken : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SingleUseAuthCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingleUseAuthCode {
            get {
                return this.SingleUseAuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SingleUseAuthCodeField, value) != true)) {
                    this.SingleUseAuthCodeField = value;
                    this.RaisePropertyChanged("SingleUseAuthCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfProcessTransaction", Namespace="http://schemas.datacontract.org/2004/07/TokenEx.Services.Models")]
    [System.SerializableAttribute()]
    public partial class ResultOfProcessTransaction : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.AVSResult AVS_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.CVVResult CVV_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransactionResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.AVSResult AVS_Result {
            get {
                return this.AVS_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.AVS_ResultField, value) != true)) {
                    this.AVS_ResultField = value;
                    this.RaisePropertyChanged("AVS_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authorization {
            get {
                return this.AuthorizationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationField, value) != true)) {
                    this.AuthorizationField = value;
                    this.RaisePropertyChanged("Authorization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.CVVResult CVV_Result {
            get {
                return this.CVV_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.CVV_ResultField, value) != true)) {
                    this.CVV_ResultField = value;
                    this.RaisePropertyChanged("CVV_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Test {
            get {
                return this.TestField;
            }
            set {
                if ((this.TestField.Equals(value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TransactionResult {
            get {
                return this.TransactionResultField;
            }
            set {
                if ((this.TransactionResultField.Equals(value) != true)) {
                    this.TransactionResultField = value;
                    this.RaisePropertyChanged("TransactionResult");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfProcessTransactionWithPAN", Namespace="http://schemas.datacontract.org/2004/07/TokenEx.Services.Models")]
    [System.SerializableAttribute()]
    public partial class ResultOfProcessTransactionWithPAN : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.AVSResult AVS_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSWeb.TokenEx_Test.CVVResult CVV_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransactionResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.AVSResult AVS_Result {
            get {
                return this.AVS_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.AVS_ResultField, value) != true)) {
                    this.AVS_ResultField = value;
                    this.RaisePropertyChanged("AVS_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authorization {
            get {
                return this.AuthorizationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationField, value) != true)) {
                    this.AuthorizationField = value;
                    this.RaisePropertyChanged("Authorization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSWeb.TokenEx_Test.CVVResult CVV_Result {
            get {
                return this.CVV_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.CVV_ResultField, value) != true)) {
                    this.CVV_ResultField = value;
                    this.RaisePropertyChanged("CVV_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Test {
            get {
                return this.TestField;
            }
            set {
                if ((this.TestField.Equals(value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TransactionResult {
            get {
                return this.TransactionResultField;
            }
            set {
                if ((this.TransactionResultField.Equals(value) != true)) {
                    this.TransactionResultField = value;
                    this.RaisePropertyChanged("TransactionResult");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfAddToken", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ResultOfAddToken : CSWeb.TokenEx_Test.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AVSResult", Namespace="http://schemas.datacontract.org/2004/07/TokenEx.Services.Models")]
    [System.SerializableAttribute()]
    public partial class AVSResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetMatchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalMatch {
            get {
                return this.PostalMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalMatchField, value) != true)) {
                    this.PostalMatchField = value;
                    this.RaisePropertyChanged("PostalMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetMatch {
            get {
                return this.StreetMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetMatchField, value) != true)) {
                    this.StreetMatchField = value;
                    this.RaisePropertyChanged("StreetMatch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVVResult", Namespace="http://schemas.datacontract.org/2004/07/TokenEx.Services.Models")]
    [System.SerializableAttribute()]
    public partial class CVVResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.tokenex.com", ConfigurationName="TokenEx_Test.ITokenServices")]
    public interface ITokenServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/Tokenize", ReplyAction="https://api.tokenex.com/ITokenServices/TokenizeResponse")]
        CSWeb.TokenEx_Test.ResultOfAddToken Tokenize(CSWeb.TokenEx_Test.TokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/Tokenize", ReplyAction="https://api.tokenex.com/ITokenServices/TokenizeResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfAddToken> TokenizeAsync(CSWeb.TokenEx_Test.TokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/TokenizeFromEncryptedValue", ReplyAction="https://api.tokenex.com/ITokenServices/TokenizeFromEncryptedValueResponse")]
        CSWeb.TokenEx_Test.ResultOfTokenizeFromEncryptedValue TokenizeFromEncryptedValue(CSWeb.TokenEx_Test.TokenizeFromEncryptedValueAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/TokenizeFromEncryptedValue", ReplyAction="https://api.tokenex.com/ITokenServices/TokenizeFromEncryptedValueResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfTokenizeFromEncryptedValue> TokenizeFromEncryptedValueAsync(CSWeb.TokenEx_Test.TokenizeFromEncryptedValueAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ValidateToken", ReplyAction="https://api.tokenex.com/ITokenServices/ValidateTokenResponse")]
        CSWeb.TokenEx_Test.ResultOfValidateToken ValidateToken(CSWeb.TokenEx_Test.ValidateTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ValidateToken", ReplyAction="https://api.tokenex.com/ITokenServices/ValidateTokenResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfValidateToken> ValidateTokenAsync(CSWeb.TokenEx_Test.ValidateTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/Detokenize", ReplyAction="https://api.tokenex.com/ITokenServices/DetokenizeResponse")]
        CSWeb.TokenEx_Test.ResultOfDetokenize Detokenize(CSWeb.TokenEx_Test.DetokenizeAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/Detokenize", ReplyAction="https://api.tokenex.com/ITokenServices/DetokenizeResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfDetokenize> DetokenizeAsync(CSWeb.TokenEx_Test.DetokenizeAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/DeleteToken", ReplyAction="https://api.tokenex.com/ITokenServices/DeleteTokenResponse")]
        CSWeb.TokenEx_Test.ResultOfDeleteToken DeleteToken(CSWeb.TokenEx_Test.DeleteTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/DeleteToken", ReplyAction="https://api.tokenex.com/ITokenServices/DeleteTokenResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfDeleteToken> DeleteTokenAsync(CSWeb.TokenEx_Test.DeleteTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/GetSingleUseAuthToken", ReplyAction="https://api.tokenex.com/ITokenServices/GetSingleUseAuthTokenResponse")]
        CSWeb.TokenEx_Test.ResultOfGetSingleUseAuthToken GetSingleUseAuthToken(CSWeb.TokenEx_Test.GetSingleUseAuthTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/GetSingleUseAuthToken", ReplyAction="https://api.tokenex.com/ITokenServices/GetSingleUseAuthTokenResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfGetSingleUseAuthToken> GetSingleUseAuthTokenAsync(CSWeb.TokenEx_Test.GetSingleUseAuthTokenAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransaction", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionResponse")]
        CSWeb.TokenEx_Test.ResultOfProcessTransaction ProcessTransaction(CSWeb.TokenEx_Test.ProcessTransationAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransaction", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransaction> ProcessTransactionAsync(CSWeb.TokenEx_Test.ProcessTransationAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransactionWithPAN", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionWithPANResponse")]
        CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN ProcessTransactionWithPAN(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransactionWithPAN", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionWithPANResponse")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN> ProcessTransactionWithPANAsync(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransactionWithEncryptedPAN", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionWithEncryptedPANResponse" +
            "")]
        CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN ProcessTransactionWithEncryptedPAN(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.tokenex.com/ITokenServices/ProcessTransactionWithEncryptedPAN", ReplyAction="https://api.tokenex.com/ITokenServices/ProcessTransactionWithEncryptedPANResponse" +
            "")]
        System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN> ProcessTransactionWithEncryptedPANAsync(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenServicesChannel : CSWeb.TokenEx_Test.ITokenServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServicesClient : System.ServiceModel.ClientBase<CSWeb.TokenEx_Test.ITokenServices>, CSWeb.TokenEx_Test.ITokenServices {
        
        public TokenServicesClient() {
        }
        
        public TokenServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSWeb.TokenEx_Test.ResultOfAddToken Tokenize(CSWeb.TokenEx_Test.TokenAction action) {
            return base.Channel.Tokenize(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfAddToken> TokenizeAsync(CSWeb.TokenEx_Test.TokenAction action) {
            return base.Channel.TokenizeAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfTokenizeFromEncryptedValue TokenizeFromEncryptedValue(CSWeb.TokenEx_Test.TokenizeFromEncryptedValueAction action) {
            return base.Channel.TokenizeFromEncryptedValue(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfTokenizeFromEncryptedValue> TokenizeFromEncryptedValueAsync(CSWeb.TokenEx_Test.TokenizeFromEncryptedValueAction action) {
            return base.Channel.TokenizeFromEncryptedValueAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfValidateToken ValidateToken(CSWeb.TokenEx_Test.ValidateTokenAction action) {
            return base.Channel.ValidateToken(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfValidateToken> ValidateTokenAsync(CSWeb.TokenEx_Test.ValidateTokenAction action) {
            return base.Channel.ValidateTokenAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfDetokenize Detokenize(CSWeb.TokenEx_Test.DetokenizeAction action) {
            return base.Channel.Detokenize(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfDetokenize> DetokenizeAsync(CSWeb.TokenEx_Test.DetokenizeAction action) {
            return base.Channel.DetokenizeAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfDeleteToken DeleteToken(CSWeb.TokenEx_Test.DeleteTokenAction action) {
            return base.Channel.DeleteToken(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfDeleteToken> DeleteTokenAsync(CSWeb.TokenEx_Test.DeleteTokenAction action) {
            return base.Channel.DeleteTokenAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfGetSingleUseAuthToken GetSingleUseAuthToken(CSWeb.TokenEx_Test.GetSingleUseAuthTokenAction action) {
            return base.Channel.GetSingleUseAuthToken(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfGetSingleUseAuthToken> GetSingleUseAuthTokenAsync(CSWeb.TokenEx_Test.GetSingleUseAuthTokenAction action) {
            return base.Channel.GetSingleUseAuthTokenAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfProcessTransaction ProcessTransaction(CSWeb.TokenEx_Test.ProcessTransationAction action) {
            return base.Channel.ProcessTransaction(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransaction> ProcessTransactionAsync(CSWeb.TokenEx_Test.ProcessTransationAction action) {
            return base.Channel.ProcessTransactionAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN ProcessTransactionWithPAN(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action) {
            return base.Channel.ProcessTransactionWithPAN(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN> ProcessTransactionWithPANAsync(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action) {
            return base.Channel.ProcessTransactionWithPANAsync(action);
        }
        
        public CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN ProcessTransactionWithEncryptedPAN(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action) {
            return base.Channel.ProcessTransactionWithEncryptedPAN(action);
        }
        
        public System.Threading.Tasks.Task<CSWeb.TokenEx_Test.ResultOfProcessTransactionWithPAN> ProcessTransactionWithEncryptedPANAsync(CSWeb.TokenEx_Test.ProcessTransactionWithPANAction action) {
            return base.Channel.ProcessTransactionWithEncryptedPANAsync(action);
        }
    }
}
